name: deploy_frontend
# Deploys when push is made from frontend folder

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.33.1
        inlineScript: |
            az storage blob upload-batch --account-name azresumechallenge -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.33.1
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumesc" --name "azureresumesc" --resource-group "AzureResumeChallenge"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()